version: '3'
services:
  ftp_server:
    image: stilliard/pure-ftpd
    container_name: ftp-server
    ports:
      - "21:21"
      - "30000-30009:30000-30009"

    environment:
      - PUBLICHOST=127.0.0.1
      - FTP_USER_NAME=uname
      - FTP_USER_PASS=uP@ssw0rd
      - FTP_USER_HOME=/home/ubuntu　 # "/"だけだとFTPサーバへログインできない

    restart: always
